#!/usr/bin/env python3
"""
Generates an ECDSA P-256 keypair for AURA firmware signing.

Outputs:
  - private.pem  : PEM-encoded private key (KEEP SECURE, never ship on device)
  - public.h     : C header with embedded DER public key for firmware_keys.h

Usage:
    python generate_keypair.py [--out-dir ./keys]
"""

import argparse
import os
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import ec


def parse_args():
    parser = argparse.ArgumentParser(description="AURA firmware signing keypair generator")
    parser.add_argument("--out-dir", default="./keys", help="Output directory for keys")
    return parser.parse_args()


def der_hex(data: bytes) -> str:
    return ", ".join(f"0x{b:02x}" for b in data)


def main():
    args = parse_args()
    os.makedirs(args.out_dir, exist_ok=True)

    private_key = ec.generate_private_key(ec.SECP256R1())
    public_key = private_key.public_key()

    pem_private = private_key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    )

    with open(os.path.join(args.out_dir, "private.pem"), "wb") as f:
        f.write(pem_private)
    print(f"Private key: {os.path.join(args.out_dir, 'private.pem')}", file=sys.stderr)

    der_public = public_key.public_bytes(
        encoding=serialization.Encoding.DER,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    )

    hex_bytes = der_hex(der_public)

    header = f"""// Auto-generated by generate_keypair.py — DO NOT EDIT MANUALLY
#ifndef AURA_FIRMWARE_KEYS_H
#define AURA_FIRMWARE_KEYS_H

#include <stdint.h>
#include <stddef.h>

// ECDSA P-256 public key in DER SubjectPublicKeyInfo format (length: {len(der_public)} bytes)
// Generated from: {os.path.join(args.out_dir, 'private.pem')}
static constexpr uint8_t kFirmwareSigningKey[] = {{ {hex_bytes} }};
static constexpr size_t kFirmwareSigningKeyLen = {len(der_public)};

// Signature: 64-byte compact (r || s) for ECDSA P-256
static constexpr size_t kSignatureLen = 64;

#endif // AURA_FIRMWARE_KEYS_H
"""

    with open(os.path.join(args.out_dir, "public.h"), "w") as f:
        f.write(header)
    print(f"Public key header: {os.path.join(args.out_dir, 'public.h')}", file=sys.stderr)


if __name__ == "__main__":
    import sys
    main()
